<?php

return [
    "DB_HOST" => "localhost",
    "DB_NAME" => "arma3life",
    "DB_USER" => "armawebconnect",
    "DB_PASS" => "8YKstFn =>W+S7b =>DB =>U+W",
    "results_per_page" => 20 ,
    "alits_life_4" => false,
    "playerView" => false,
    "sql_smartPhone" => false,
    "enable_game_query" => true,
    "lvlcop" => 7,
    "lvlmed" => 5,
    "lvladmin" => 5,
    "lvldonator" => 5,
    "icon1" => "Dave",
    "icon2" => "Sam",
    "icon3" => "Joe",
    "icon4" => "Kerry",
    "icon5" => "Connie",
    "icon6" => "Jess",
    "staff_levels" => 3,
    "P_VIEW_STAFF" => 3,
    "P_VIEW_VEHICLES" => 2,
    "P_VIEW_HOUSES" => 2,
    "P_VIEW_GANGS" => 2,
    "P_VIEW_WANTED" => 2,
    "P_VIEW_PLAYER" => 1,
    "P_VIEW_LICENCES" => 1,
    "P_EDIT_STAFF" => 3,
    "P_EDIT_VEHICLES" => 3,
    "P_EDIT_HOUSES" => 3,
    "P_EDIT_GANGS" => 3,
    "P_EDIT_WANTED" => 3,
    "P_EDIT_ADMINS" => 3,
    "P_EDIT_PLAYER" => 2,
    "P_EDIT_PLAYER_INV" => 2,
    "P_EDIT_PLAYER_LICENCES" => 2,
    
    "P_ACCESS_SQL_PHONE" => 0,
    "P_ADD_NOTE" => 2
];